DATA SEGMENT
    ARRAY DB 01H, 23H, 13H, 14H, 15H, 13H, 13H  ; DEFINE ARRAY OF NUMBERS
    NUM DB 13H                                   ; DEFINE THE NUMBER TO SEARCH
    COUNT DB ?                                   ; DEFINE COUNT OF OCCURRENCES
DATA ENDS

CODE SEGMENT
START:  
    ASSUME DS: DATA, CS: CODE   ; ASSUME DATA SEGMENT FOR DS AND CODE SEGMENT FOR CS

    MOV AX, DATA               ; LOAD DATA SEGMENT ADDRESS INTO AX
    MOV DS, AX                 ; LOAD DATA SEGMENT ADDRESS INTO DS

    MOV CX, 0007H              ; SET CX TO 7 (NUMBER OF ELEMENTS IN ARRAY)
    MOV BX, 0000H              ; INITIALIZE BX (USED AS OFFSET FOR ARRAY)
    MOV AL, NUM                ; LOAD THE SEARCH NUMBER (NUM) INTO AL
    MOV DL, 00H                ; CLEAR DL (COUNTER FOR OCCURRENCES)

HERE:
    CMP AL, ARRAY[BX]          ; COMPARE NUM (AL) WITH CURRENT ARRAY ELEMENT (ARRAY[BX])
    JNE NEXT                   ; IF NOT EQUAL, JUMP TO NEXT (NO MATCH)
    INC DL                     ; IF EQUAL, INCREMENT THE COUNT IN DL
    NEXT:
    INC BX                     ; INCREMENT BX TO POINT TO NEXT ELEMENT IN ARRAY
LOOP HERE                  ; DECREMENT CX AND LOOP UNTIL CX REACHES 0

    MOV COUNT, DL              ; STORE THE FINAL COUNT OF OCCURRENCES IN COUNT

    MOV AX, 4C00H              ; TERMINATE THE PROGRAM
    INT 21H                    ; INTERRUPT 21H (TERMINATE PROGRAM)

CODE ENDS
END START